spring.application.name=the-ledger-service
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=my-password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
server.address=0.0.0.0
logging.level.org.hibernate.orm.session=ERROR
